In [1]:
##사업체수
import pandas as pd

f = pd.read_table("C://Users//82106//Downloads//_census_reqdoc_1659063002585//original//11_2019년_산업분류별(10차_대분류)_사업체수.txt",sep='^',header=None)
f = f.fillna(0)
f = f.iloc[:,1:]
f.iloc[:,0] = f.iloc[:,0].map(str)
f['읍면동코드'],f['일련번호'] = map(f.iloc[:,0].str.slice,[0,7],[7,12])
#print(f)

d = pd.read_excel("C://Users//82106//Downloads//ref_code//original//adm_code.xls",sheet_name='2019년6월')
d = d[d.iloc[:,0]=='11'] #서울특별시 정보만 추출
d = d.iloc[:,2:] #시도코드, 시도명칭 삭제
#print(d)

g = pd.read_excel("C://Users//82106//Downloads//ref_code//original//statistics_code.xls",sheet_name='집계구')
g = g.iloc[:,2:]
g = g[g.iloc[:,1].str.contains("cp_bnu_")] #원하는 사업체수 코드를 가진 row만 추출
g = g.tail(20)
#print(g)


#merge the dataframe
merge1 = pd.merge(f,d,left_on='읍면동코드',right_on=d.iloc[:,2],how='left')
merge1 = merge1.iloc[:,[0,2,4,6,8]]
merge2 = pd.merge(f,g,left_on=f.iloc[:,1],right_on=g.iloc[:,1],how='left')
merge2 = merge2.iloc[:,[1,6]]
sa_up_chae_soo = pd.concat([merge1,merge2],axis=1,join='inner')
sa_up_chae_soo = sa_up_chae_soo.iloc[:,[1,2,3,4,6]]
names = ['사업체수','일련번호','구이름','동이름','산업종류']
sa_up_chae_soo.columns = names
names = names[1:]+names[:1]
sa_up_chae_soo = sa_up_chae_soo[names]
print(sa_up_chae_soo)


##grouping by Dong name
#sucs = sa_up_chae_soo.groupby('동이름')
#sucs.get_group('가락1동')

                    1           2     3    읍면동코드   일련번호
0       1104069010009  cp_bnu_007   0.0  1104069  01000
1       1113075040022  cp_bnu_019   0.0  1113075  04002
2       1105061020017  cp_bnu_007  11.0  1105061  02001
3       1106083010002  cp_bnu_013   0.0  1106083  01000
4       1116055010048  cp_bnu_007   0.0  1116055  01004
...               ...         ...   ...      ...    ...
100502  1109071010022  cp_bnu_019   0.0  1109071  01002
100503  1116073020002  cp_bnu_012  11.0  1116073  02000
100504  1112067010006  cp_bnu_009  10.0  1112067  01000
100505  1118052030008  cp_bnu_007  13.0  1118052  03000
100506  1125073010018  cp_bnu_003   0.0  1125073  01001

[100507 rows x 5 columns]
         일련번호   구이름   동이름                       산업종류  사업체수
0       01000   성동구   송정동                   도매 및 소매업   0.0
1       04002  서대문구   신촌동  협회 및 단체, 수리  및 기타 개인 서비스업   0.0
2       02001   광진구  구의2동                   도매 및 소매업  11.0
3       01000  동대문구  전농1동           전문, 과학 및 기술 서비스업   0.0
4       01004   강서구  화곡본동                   도매 및 소매업   0.0
...       ...   ...   ...                        ...   ...
100502  01002   강북구   송중동  협회 및 단체, 수리  및 기타 개인 서비스업   0.0
100503  02000   강서구  화곡1동                 부동산업 및 임대업  11.0
100504  01000   은평구   증산동                  숙박 및 음식점업  10.0
100505  03000   금천구  독산1동                   도매 및 소매업  13.0
100506  01001   강동구  천호2동                        제조업   0.0

[100507 rows x 5 columns]

In [150]:
##종사자수
import pandas as pd

f = pd.read_table("C://Users//82106//Downloads//_census_reqdoc_1659063002585//original//11_2019년_산업분류별(10차_대분류)_종사자수.txt",sep='^',header=None)
f = f.fillna(0)
f = f.iloc[:,1:]
f.iloc[:,0] = f.iloc[:,0].map(str)
f['읍면동코드'],f['일련번호'] = map(f.iloc[:,0].str.slice,[0,7],[7,12])
#print(f)

d = pd.read_excel("C://Users//82106//Downloads//ref_code//original//adm_code.xls",sheet_name='2019년6월')
d = d[d.iloc[:,0]=='11'] #서울특별시 정보만 추출
d = d.iloc[:,2:] #시도코드, 시도명칭 삭제
#print(d)

g = pd.read_excel("C://Users//82106//Downloads//ref_code//original//statistics_code.xls",sheet_name='집계구')
g = g.iloc[:,2:]
g = g[g.iloc[:,1].str.contains("cp_bem_")] #원하는 종사자수 코드를 가진 row만 추출
g = g.tail(20)
#print(g)


#merge the dataframe
merge1 = pd.merge(f,d,left_on='읍면동코드',right_on=d.iloc[:,2],how='left')
merge1 = merge1.iloc[:,[0,2,4,6,8]]
merge2 = pd.merge(f,g,left_on=f.iloc[:,1],right_on=g.iloc[:,1],how='left')
merge2 = merge2.iloc[:,[1,6]]
jong_sa_ja_soo = pd.concat([merge1,merge2],axis=1,join='inner')
jong_sa_ja_soo = jong_sa_ja_soo.iloc[:,[1,2,3,4,6]]
names = ['종사자수','일련번호','구이름','동이름','산업종류']
jong_sa_ja_soo.columns = names
names = names[1:]+names[:1]
jong_sa_ja_soo = jong_sa_ja_soo[names]
#print(jong_sa_ja_soo)



##grouping by Dong name
#jsjs = jong_sa_ja_soo.groupby('동이름')
#jsjs.get_group('가락1동')

         일련번호  구이름   동이름                       산업종류  종사자수
8287    01022  송파구  가락1동                 부동산업 및 임대업   0.0
8452    01021  송파구  가락1동                    교육 서비스업   0.0
10252   01023  송파구  가락1동         공공행정, 국방 및 사회보장 행정  50.0
10721   01020  송파구  가락1동  협회 및 단체, 수리  및 기타 개인 서비스업  21.0
11176   01020  송파구  가락1동                  숙박 및 음식점업  14.0
...       ...  ...   ...                        ...   ...
103156  01021  송파구  가락1동                   자료없는 집계구   0.0
103159  01021  송파구  가락1동                   자료없는 집계구   0.0
103160  01023  송파구  가락1동                   자료없는 집계구   0.0
103161  01023  송파구  가락1동                   자료없는 집계구   0.0
103162  01023  송파구  가락1동                   자료없는 집계구   0.0

[98 rows x 5 columns]