In [4]:
import mapboxgl
import os

MAPBOX_API_KEY = 'pk.eyJ1IjoiaHlldHRvbmllIiwiYSI6ImNsNng2ODJhcTJvY20zZW5zd2ZtdXZicDMifQ.x8zu89vFSPljvCpC4A-IzA'

import pydeck as pdk

In [ ]:
import shapefile
import json

path = 'pyshp/shapefiles/blockgroups'
sf = shapefile.Reader(path)

fields = sf.fields[1:]
field_names = [field[0] for field in fields]

buffer = []
for sr in sf.shapeRecords():
    atr = dict(zip(field_names, sr.record))
    
    geom = sr.shape.__geo_interface__
    buffer.append(dict(type='Feature',geometry=geom, properties=atr))
    

geojson = open('pyshp-demo.geojson','w')
geojson.write(json.dumps({'type':'FeatureCOllection', "features":buffer},indent=2,ensure_ascii=False))
geojson.close()

In [93]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'S-Core Dream'
plt.rcParams['figure.figsize'] = (10,10)

sample = "C://Users//82106//Downloads//_census_data_2021_bnd_oa_bnd_oa_11_2021_2021//bnd_oa_11_2021_2021_2Q.shp"
seoul = gpd.read_file(sample)
#seoul = gpd.GeoDataFrame(seoul)
seoul = pd.DataFrame(seoul)
seoul


sucs = pd.read_csv("C://Datacampus_project//사업체수.csv")
sucs['집계구번호'] = sucs['집계구번호'].astype(object)
sucs = sucs.rename(columns={'집계구번호':'TOT_REG_CD'})
#sucs = gpd.GeoDataFrame(sucs)


#Final = seoul.merge(sucs, on='TOT_REG_CD',how='right')
#Final = gpd.sjoin(seoul,sucs, how='right', op='within')
#Final


#Final.plot(column='사업체수', cmap="OrRd")

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import geopandas as gpd
from census import Census
from us import states

c=Census("b7063b71bdc4d08bc9885acf4162fcd1ac8a6a05")

In [97]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'S-Core Dream'
plt.rcParams['figure.figsize'] = (10,10)

sample = "C://Users//82106//Downloads//_census_data_2021_bnd_oa_bnd_oa_11_2021_2021//bnd_oa_11_2021_2021_2Q.shp"
seoul = gpd.read_file(sample)
#seoul = gpd.GeoDataFrame(seoul)
seoul = pd.DataFrame(seoul)

sucs = pd.read_csv("C://Datacampus_project//사업체수.csv")
sucs['집계구번호'] = sucs['집계구번호'].astype(object)
sucs = sucs.rename(columns={'집계구번호':'TOT_REG_CD'})

Final = seoul.merge(sucs, on='TOT_REG_CD',how='right')
Final

C:\Users\82106\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\reshape\merge.py:906: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  key_col = Index(rvals)

,BASE_DATE,ADM_CD,TOT_REG_CD,geometry,산업분류,사업체수
0,NaN,NaN,1104069010009,None,도매 및 소매업,0.0
1,NaN,NaN,1113075040022,None,"협회 및 단체, 수리 및 기타 개인 서비스업",0.0
2,NaN,NaN,1105061020017,None,도매 및 소매업,11.0
3,NaN,NaN,1106083010002,None,"전문, 과학 및 기술 서비스업",0.0
4,NaN,NaN,1116055010048,None,도매 및 소매업,0.0
...,...,...,...,...,...,...
100502,NaN,NaN,1109071010022,None,"협회 및 단체, 수리 및 기타 개인 서비스업",0.0
100503,NaN,NaN,1116073020002,None,부동산업 및 임대업,11.0
100504,NaN,NaN,1112067010006,None,숙박 및 음식점업,10.0
100505,NaN,NaN,1118052030008,None,도매 및 소매업,13.0
100506,NaN,NaN,1125073010018,None,제조업,0.0

In [ ]:
import pandas as pd

f = pd.read_csv("C://Users//82106//Downloads//서울특별시 공공자전거 이용정보(시간대별)_22.06.csv", encoding='cp949')

#f.head()
f.shape()